# This workflow will launch at every 00:00
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

name: Launch Scala Steward

jobs:
  scala-steward:
    runs-on: ubuntu-latest
    name: Launch Scala Steward
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - name: Launch Scala Steward
        uses: scala-steward-org/scala-steward-action@v2
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          author-email: thayakorn@zipmex.com
          author-name: zipmex-deploy
